### PR TITLE
Added possibility to skip reparse points (symlinks)

### PR DESCRIPTION
**Pull request by dermalikmann**

### CODE REVIEW

**Comment by TanninOne** [comment]
Have you verified this works for both "directory symbolic links" as well as "junction points"? I find the documentation for FILE_ATTRIBUTE_REPARSE_POINT a bit imprecise and I never got around to testing.

**Comment by dermalikmann** [comment]
I was just about to test this, but in theory they should be the same (at least in the view point of the attributes), because the only (real) difference is how windows processes it's content [(reference)](https://superuser.com/a/343079/650977). For windows, both are reparse points.  I will update this in a few minutes with my test.

**Comment by dermalikmann** [comment]
Sorry, I had to do some private stuff...
Yes, it sucessfully skips junctions AND (directory) symlinks.

**Comment by TanninOne** [comment]
Perfect, thank you!

**Pull request merged**
